routes:
  - id: users
    uris:
      - /
      - /*
    plugins:
      openid-connect:
        client_id: apisix
        client_secret: secret
        discovery: http://authn_srv:8080/default/.well-known/openid-configuration
        bearer_only: true
        use_jwks: true
        ssl_verify: false
        _meta:
          priority: 2599

      serverless-post-function:
        phase: rewrite
        functions:
        - |
          return function(conf, ctx)
            local core = require("apisix.core")
            local cjson = require("cjson.safe")

            local userinfo = core.request.header(ctx, "X-Userinfo")
            local claims = userinfo and cjson.decode(ngx.decode_base64(userinfo))

            if claims and claims.sub then
              core.request.set_header(ctx, "X-Userinfo-Sub", claims.sub)
            end
          end
        _meta:
          priority: 2580
          
      authz-casbin:
        model_path: casbin/acl_model.conf
        policy_path: casbin/acl_perm.csv
        username: X-Userinfo-Sub
        _meta:
          priority: 2560

    upstream:
      type: roundrobin
      nodes:
        "upstream:80": 1

#END