# --- Gateway Connection ---
gateways:
  duckdb:
    connection:
      type: duckdb
      database: ./.temp/db.db

default_gateway: duckdb

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: duckdb
  start: 2026-04-06 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: false
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections

before_all:
  - |
    CREATE SCHEMA IF NOT EXISTS util;

    CREATE OR REPLACE MACRO util.assert(ok, fail_message) AS
      CASE
        WHEN ok THEN TRUE
        ELSE error(fail_message)
      END;
