services:
  netl:
    image: sogis/netl
    container_name: netl
    user: "${NETL_UID}:${NETL_GID}"
    entrypoint: ["sleep", "20h"]
    init: true
    volumes:
      - type: bind
        source: ../netl_source
        target: /netl
      - type: bind
        source: ../repo
        target: /netl/repo
      - type: bind
        source: ../netl_build
        target: /netl/netl_build